disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - large_tuple
  - line_length
  - nesting
  - opening_brace
  - override_in_extension
  - prohibited_interface_builder
  - redundant_void_return # Handled by SwiftFormat
  - single_test_class
  - todo
  - trailing_comma
  - type_body_length
  - type_name

opt_in_rules:
  - async_without_await
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - joined_default_parameter
  - last_where
  - legacy_random
  - lower_acl_than_parent
  - modifier_order
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - prohibited_interface_builder
  - prohibited_super_call
  - reduce_boolean
  - reduce_into
  - redundant_type_annotation
  - self_binding
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - superfluous_disable_command
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument

modifier_order:
  # Override the default, which would have us do `nonisolated public`, because we hold acl to be more important than isolation
  preferred_modifier_order: ["override", "acl", "isolation", "final"]

excluded:
  - .build
  - Scripts
